package com.sma.smartauto.exception;

public enum ApiErrorCode {
	ACCESS_DENIED, MISSING_QUERY_PARAM, INVALID_API_TOKEN, BAD_CREDENTIALS, CLIENT_NOT_FOUND, INVALID_INPUT, INVALID_CODE, CODE_EXPIRED, CODE_ALREADY_USED,
	ASSET_IDENTIFIER_ALREADY_EXISTS, RESOURCE_NOT_FOUND, CODE_ERROR, NO_ASSET_FOR_IDENTIFIER_TYPE
}
